In [2]:
#Question 1

import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)

print("Mean Of The Above Matrix Is =",np.sum(x)/len(x))


#Second Method
print("Mean Of The Above Matrix Is =",np.mean(x))


Formed Matrix Is 
 [[0.99800607]
 [0.7574995 ]
 [0.07181819]
 [0.9043143 ]
 [0.55821109]
 [0.43712558]
 [0.58757619]
 [0.07190643]
 [0.21304392]
 [0.80283741]]
Mean Of The Above Matrix Is = 0.5402338670422656
Mean Of The Above Matrix Is = 0.5402338670422656


In [3]:
#Question 2

x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)

print("Variance of the formed matrix is =",np.var(x))


print("Standard deviation of the formed matrix is =",np.std(x))
#Second Method For standard deviation
print("Standard deviation of the formed matrix is =",np.sqrt(np.var(x)))


Formed Matrix Is 
 [[0.03873406]
 [0.21878337]
 [0.80656697]
 [0.03625377]
 [0.65204628]
 [0.84847263]
 [0.19885061]
 [0.9402562 ]
 [0.05710026]
 [0.95622758]
 [0.5007291 ]
 [0.71818579]
 [0.87380812]
 [0.89446968]
 [0.74969635]
 [0.88051332]
 [0.55118264]
 [0.65127193]
 [0.57524107]
 [0.89984   ]]
Variance of the formed matrix is = 0.09828106769565295
Standard deviation of the formed matrix is = 0.3134981143414629
Standard deviation of the formed matrix is = 0.3134981143414629


In [4]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.matmul(A,B)
print("Matrix Formed After Multiplication\n",x)


print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[4.84678051 5.40235763 6.15099481 4.52479296 6.91922792 6.49750589
  5.04306305 6.02961579 4.66829914 6.09793504 7.06306772 5.05849116
  5.56183787 5.77372774 5.27964    6.51261116 4.94824382 4.96352869
  5.46414127 5.67851525 5.93752491 5.14957427 5.70042961 6.1107263
  5.36972834]
 [3.93075619 5.14884043 5.19962136 4.57131342 5.80182404 5.56556513
  4.65841147 4.68295928 3.84387997 4.93872909 5.5910401  4.3413116
  5.01635095 5.63193948 4.36775554 5.10357492 4.49618822 4.58947643
  5.27003799 4.67359873 5.35412188 4.68639842 4.71011388 4.97424748
  4.52074356]
 [4.56746165 4.6432021  5.4175119  5.19179894 5.69114371 5.00228202
  5.09737635 5.15837407 3.56288883 4.37931494 6.80588877 4.55793397
  4.21044396 5.03388697 5.08190299 5.16705436 5.07983931 4.18738665
  5.03315125 4.10154773 5.4032251  5.06004429 4.31057936 4.84137476
  4.53404994]
 [3.87918541 4.20031877 4.73307831 3.72190211 5.25530063 4.44118531
  4.58517312 4.67889482 3.73499089 4.195

In [84]:
#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))    

[[0.92065213]
 [0.41306738]
 [0.20974384]
 [0.35570468]
 [0.88816119]
 [0.64611894]
 [0.62900412]
 [0.37754222]
 [0.93865497]
 [0.86094524]]



After performing given function
[[0.71517496]
 [0.60182315]
 [0.55224457]
 [0.58800026]
 [0.70851056]
 [0.65613534]
 [0.65226362]
 [0.59328018]
 [0.71882789]
 [0.7028581 ]]
